apiVersion: v1
kind: ConfigMap
metadata:
  name: payment-service-config
  namespace: vexeviet
data:
  NODE_ENV: "production"
  PAYMENT_SERVICE_PORT: "3003"
  LOG_LEVEL: "info"
  VNPAY_VERSION: "2.1.0"
  VNPAY_CURRENCY: "VND"
  VNPAY_LOCALE: "vn"
